-- luacheck: ignore 113
local stub = require("wowstub")

test("Count zählt pro Charakter, ID und Zone", function()
    local DB = stub.load()
    local ns = DB:Register("combat", { area = "Core", zones = true })
    ns:Count("kill", 299, 1429)
    ns:Count("kill", 299, 1429)
    ns:Count("kill", 6, 12)
    eq(ns:GetCount("kill", 299), 2, "kill 299")
    eq(ns:GetCount("kill"), 3, "alle kills")
    eq(ns:GetZones("kill", 299)[1429], 2, "Zone")
    eq(GlimpseDB_Core.combat.version, 1, "Version")
end)

test("Ohne zones wird keine Zone gespeichert", function()
    local DB = stub.load()
    local ns = DB:Register("plain", { area = "Core" })
    ns:Count("x", 1, 12)
    eq(next(ns:GetZones("x", 1)), nil, "keine Zonen")
end)

test("account summiert alle eigenen Charaktere", function()
    local DB = stub.load()
    DB:Register("combat", { area = "Core" }):Count("kill", 1)
    local saved = stub.saved()

    DB = stub.restart(saved, { guid = "Player-1-00000002", name = "Twink" })
    local ns = DB:Register("combat", { area = "Core" })
    ns:Count("kill", 1, nil, 4)
    eq(ns:GetCount("kill", 1), 4, "char")
    eq(ns:GetCount("kill", 1, "account"), 5, "account")
    eq(#DB:GetCharacters(), 2, "zwei Charaktere")
    eq(select(1, DB:GetCharacterInfo(DB:GetCharacters()[1])), "Twink", "aktueller zuerst")
end)

test("Startwert nur auf Wunsch und nur einmal", function()
    local DB = stub.load()
    local ns = DB:Register("stats", { area = "Core" })
    eq(ns:SetBaseline("fish", 0, 100), true, "gesetzt")
    eq(ns:SetBaseline("fish", 0, 200), false, "nicht überschrieben")
    ns:Count("fish")
    eq(ns:GetCount("fish"), 1, "ohne baseline")
    eq(ns:GetCount("fish", nil, { sources = { "own", "baseline" } }), 101, "mit baseline")
end)

test("Erster und letzter Zeitpunkt", function()
    local DB = stub.load()
    local ns = DB:Register("combat", { area = "Core" })
    ns:Count("kill", 5)
    local first = stub.serverTime
    stub.serverTime = stub.serverTime + 500
    ns:Count("kill", 5)
    local a, b = ns:GetSeen("kill", 5)
    eq(a, first, "erster")
    eq(b, first + 500, "letzter")
end)

test("Callback bei jeder Änderung", function()
    local DB = stub.load()
    local seen = {}
    DB.RegisterCallback(seen, DB.EVENT_CHANGED, function(_, ns, kind, id) seen[#seen + 1] = ns .. kind .. id end)
    DB:Register("combat", { area = "Core" }):Count("kill", 7)
    eq(seen[1], "combatkill7", "Callback")
end)
