-- luacheck: ignore 113
local stub = require("wowstub")

test("Namen: speichern und lesen in der Sprache", function()
    local DB = stub.load()
    local ns = DB:Register("names", { area = "Misc" })
    eq(ns:SetLabel("npc", 299, "Wolf", "enUS"), true, "neu")
    eq(ns:SetLabel("npc", 299, "Wolf", "enUS"), false, "unverändert")
    eq(ns:SetLabel("npc", 299, "Wolf", "deDE"), true, "andere Sprache")
    ns:SetLabel("npc", 300, "Bär", "deDE")
    eq(ns:GetLabel("npc", 299, "deDE"), "Wolf", "deDE")
    local name, locale = ns:GetLabel("npc", 300, "enUS")
    eq(name, "Bär", "Name aus anderer Sprache")
    eq(locale, "deDE", "Sprache dazu")
    eq(ns:GetLabel("npc", 5), nil, "unbekannt")
end)

test("Namen: ungültige Eingaben werden verworfen", function()
    local DB = stub.load()
    local ns = DB:Register("names", { area = "Misc" })
    eq(ns:SetLabel("npc", 1, ""), false, "leer")
    eq(ns:SetLabel("npc", 1, 5), false, "Zahl")
    eq(ns:SetLabel("npc", 1, string.rep("x", 200)), false, "zu lang")
    eq(ns:SetLabel(nil, 1, "x"), false, "ohne Art")
end)
