-- luacheck: ignore 113 122
local stub = require("wowstub")

test("Nur ein Schreiber pro Namespace", function()
    local DB = stub.load()
    DB:Register("combat", { area = "Core" })
    local ok = pcall(DB.Register, DB, "combat", { area = "Core" })
    eq(ok, false, "zweites Register")
end)

test("Get liest, kann aber nicht schreiben", function()
    local DB = stub.load()
    DB:Register("combat", { area = "Core" }):Count("kill", 1)
    local reader = DB:Get("combat")
    eq(reader:GetCount("kill", 1), 1, "lesen")
    eq(reader.Count, nil, "kein Count")
    eq(reader:IsWriter(), false, "Leser")
end)

test("LoadOnDemand-Bereich wird beim Register geladen", function()
    local DB = stub.load()
    eq(DB:IsAreaLoaded("Professions"), false, "vorher")
    local ns = DB:Register("fishing", { area = "Professions" })
    ns:Count("catch", 6303)
    eq(stub.loaded["Glimpse_Database_Professions"], true, "Addon geladen")
    eq(GlimpseDB_Professions.fishing.own.counts[1].catch[6303], 1, "SavedVariables")
end)

test("Get lädt den Bereich in einer neuen Sitzung", function()
    local DB = stub.load()
    DB:Register("fishing", { area = "Professions" }):Count("catch", 1)
    DB = stub.restart(stub.saved())
    stub.loaded = {}
    eq(DB:IsAreaLoaded("Professions"), false, "nicht geladen")
    eq(DB:Get("fishing"):GetCount("catch", 1), 1, "gelesen")
end)

test("Abgeschalteter Bereich liefert Grund", function()
    local DB = stub.load()
    stub.disabled["Glimpse_Database_Misc"] = true
    local ns, reason = DB:Register("misc")
    eq(ns, nil, "kein Namespace")
    eq(reason, "DISABLED", "Grund")
end)

test("Migration bei neuer Schema-Version", function()
    local DB = stub.load()
    DB:Register("combat", { area = "Core" }):Count("kill", 1)
    DB = stub.restart(stub.saved())
    local called
    DB:Register("combat", { area = "Core", version = 2, migrate = function(_, from, to) called = from .. ">" .. to end })
    eq(called, "1>2", "migrate")
    eq(GlimpseDB_Core.combat.version, 2, "neue Version")
end)

test("Neuere Daten als der Code werden nicht angefasst", function()
    local DB = stub.load()
    DB:Register("combat", { area = "Core", version = 3 }):Count("kill", 1)
    DB = stub.restart(stub.saved())
    local ns, reason = DB:Register("combat", { area = "Core", version = 2 })
    eq(ns, nil, "abgelehnt")
    eq(reason, "NEWER_DATA", "Grund")
end)

test("Umzug in einen anderen Bereich", function()
    local DB = stub.load()
    DB:Register("loot", { area = "Misc" }):Count("drop", 2589)
    DB = stub.restart(stub.saved())
    local ns = DB:Register("loot", { area = "Gathering" })
    eq(ns:GetCount("drop", 2589), 1, "Daten mitgenommen")
    eq(GlimpseDB_Misc.loot, nil, "alter Bereich leer")
end)

test("ResetArea leert den Bereich", function()
    local DB = stub.load()
    local ns = DB:Register("combat", { area = "Core" })
    ns:Count("kill", 1)
    DB:ResetArea("Core")
    eq(ns:GetCount("kill", 1), 0, "leer")
    ns:Count("kill", 1)
    eq(ns:GetCount("kill", 1), 1, "schreibt wieder")
end)

test("Alte Tabelle im Global GlimpseDB wird beim nächsten ADDON_LOADED ersetzt", function()
    local DB = stub.load()
    _G.GlimpseDB = { profileKeys = {} }
    stub.fire("ADDON_LOADED", "Glimpse")
    eq(_G.GlimpseDB, DB, "API wieder da")
end)
